Kanji support
alexay7/jpdb-production pull request #3
Opened 2024-03-05 14:50 UTC by ArmoryFou

Fixed

2024-03-05 14:54 UTC, ArmoryFou commented
@alexay7 quería meter esto para prácticar escribir kanji, no solo escribirlo en romaji o hiragana. ¿Qué opinas?

2024-03-11 15:47 UTC, alexay7 requested changes

2024-03-11 15:47 UTC, alexay7 commented on content.js
> +console.log(`Correct answer (full): ${correctAnswer}`);
Quita los console logs si no hacen falta

2024-03-11 15:47 UTC, alexay7 commented on content.js
> +const correctChilds = correct.children;
Lintea todo bien

2024-03-11 15:47 UTC, alexay7 commented on content.js
> +        if(correctKanji){
Igual sería menos confuso que la comprobación fuera directamente que la longitud del correctKanji sea superior a 0

2024-03-20 22:52 UTC, alexay7 approved these changes

2024-03-20 22:52 UTC, merged